# This workflow will upload a Python Package using Twine when a release is created

name: Upload Python Package

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching *, i.e. 1.0, 20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - uses: actions/checkout@v5
    - name: Set up Python with uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
    - name: Install dependencies
      run: uv sync --managed-python
    - name: Build and publish
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.TWINE_TOKEN }}
      run: |
        uv version "${{ steps.get_version.outputs.VERSION }}"
        uv build
        uv publish dist/*

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          Release created, package download: https://pypi.org/project/certbot-dns-infomaniak/${{ steps.get_version.outputs.VERSION }}/
        draft: false
        prerelease: false
